const GOOGLE_SHEETS_CONFIG = {
    scriptURL: 'https://script.google.com/macros/s/AKfycby2coPe8VFcCQgdnLMs69A0a5HTdVMjf_IH-F5UEy3O0yc-yUsdo0y77xFuRK06jO_c/exec',
    // other config parameters...
};

// Your existing code here...